version: '3'

services:

  zookeeper:
    image: quay.io/debezium/zookeeper        
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    restart: on-failure

  kafka:
    image: quay.io/debezium/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181      
     - LOG_LEVEL=DEBUG
    restart: on-failure

  mysql_master:

    image: mysql-gtids1
    build:
      context: master
    environment:
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - 33060:3306

  mysql_slave1:

    image: mysql-gtids2
    build:
      context: slave1
    environment:
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - 33061:3306
    depends_on:
      - mysql_master

  mysql_slave2:

    image: mysql-gtids3
    build:
      context: slave2
    environment:
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - 33062:3306
    depends_on:
      - mysql_master

  proxysql:
    
    image: proxysql/proxysql:2.0.12
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf 

  postgres:
    image: quay.io/debezium/postgres:9.6     
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=inventory
     - LOG_LEVEL=TRACE

  connect:
    image: debezium/connect-jdbc
    build:
      context: debezium-jdbc
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - proxysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    restart: on-failure
